name: Update channels.m3u

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch channels.m3u from hosting
      env:
        FILE_URL: ${{ secrets.CHANNELS_FILE_URL }}
      run: |
        curl -o channels.m3u $FILE_URL

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        git add SonyLIV.m3u
        git commit -m "Update SonyLIV.m3u file." || echo "No changes to commit"

        git pull origin main --rebase
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        git push origin HEAD:main
